### ISSUE TITLE
Add Highly Cited Metric Post

### ISSUE THREAD

**Issue by rchampieux** [Metrics-Toolkit/Metrics-Toolkit#11]

**Comment by rchampieux** [comment]
@skonkiel I think you drafted this, but is it ready for publication?

**Comment by skonkiel** [comment]
@rchampieux We had discussed breaking [this drafted post](https://docs.google.com/document/d/1wMWhChVGgSIWnXHg4NsvKJFIw8OX-EQNPRp8blGtXpI/edit) out into two articles--one for "citation percentiles" and another for "highly cited awards and designations". I've been attempting to do just that for the past hour but am running into an issue: designations like Dimensions' "Highly Cited 1%" are both a percentile and a "Highly Cited" award, making the distinction moot (and potentially confusing to the end user).

@rchampieux @coateshl let's discuss in our next meeting.

**Comment by skonkiel** [comment]
@rchampieux @coateshl I've reviewed the [existing article draft](https://docs.google.com/document/d/1wMWhChVGgSIWnXHg4NsvKJFIw8OX-EQNPRp8blGtXpI/edit) and think it's ready for your review.
