### ISSUE TITLE
Add Eigenfactor Post

### ISSUE THREAD

**Issue by rchampieux** [Metrics-Toolkit/Metrics-Toolkit#12]

**Comment by rchampieux** [comment]
@coateshl Please use issue to link to post text.

**Comment by coateshl** [comment]
https://docs.google.com/document/d/108ZRgtzDMD84rAfw9Dqm3zZRA9mzxA9pesKcpLa45M4/edit

**Comment by skonkiel** [comment]
I've added my comments for review
