### ISSUE TITLE
Posts with transparency fields that should be updated.

### ISSUE THREAD

**Issue by rchampieux** [Metrics-Toolkit/Metrics-Toolkit#45]
* Citations, data
* Downloads, Articles
* Downloads, Books
* Downloads, Software
* F1000
* ~FWCI~
* Github
* h-index
* RCR

**Comment by rchampieux** [comment]
Here are the metric assignments:  https://docs.google.com/spreadsheets/d/1ZKgGPO-aJLl0AUDZv5XS09Hrm87IaKkIYIpbWApj5PQ/edit#gid=0

**Comment by rchampieux** [comment]
The FWCI post has been updated.

**Comment by rchampieux** [comment]
Please review and make necessary changes to any metrics noted above for which you are the lead.

**Comment by skonkiel** [comment]
~Citations, data~
~RCR~

**Comment by coateshl** [comment]
Downloads, Articles - done
Downloads, Books - done
Downloads, Software - done
F1000 - in progress
Github - done
h-index - done

**Comment by coateshl** [comment]
F1000 - done

**Comment by rchampieux** [comment]
Robin will do updates in WP.
