### ISSUE TITLE
Document Github Workflow for Updated or Creating Metrics Posts

### ISSUE THREAD

**Issue by rchampieux** [Metrics-Toolkit/Metrics-Toolkit#52]

**Comment by rchampieux** [comment]
Workflow Draft:

* New metric post creations and revisions will be submitted through and finalized via Github through two optional routes:

1). An issue (an editorial board guide will define how issues should be titled and the information they should include).  We can also add this info to our readme documentation.

2).  A pull request.  New posts can utilize the schema markdown template located in our metrics folder (https://github.com/Metrics-Toolkit/Metrics-Toolkit/blob/master/Metrics/schema.md).  Revisions can be made on existing files.  In either case, contributors/editors will be asked to create 

* Notifications will alert our repository admins to new pull requests and issues, which can then trigger the appropriate review/approval.

*  Once the new post or revision is approved for publication, the following steps will occur:

1).  The issue will be reflected in a new metrics file or revision, submitted as a pull request (on a new branch) and merged with the mater branch.  The branch created for the pull request will be deleted.

OR

If originally submitted as a pull request, it will be merged with the master branch and the obsolete branch will be deleted.

**The pull request should be associated with the label "Update in WP" to facilitate the next step.**

3).  The post or revision is manually added to or revised in our WP site.  The "Update in WP" label can be used to facilitate a regular, batch updating schedule in WP.

4).  The label "Update in WP" is removed from the pull request.

**Comment by skonkiel** [comment]
I'm having a little trouble understanding this workflow and how it differs from what Heather's outlined in the [Editorial Process](https://docs.google.com/document/d/12fK83nnFPTq91ut0eFTUeVq9oW6XuVc1CtX6UZlk7R4/edit) document.  It's just the steps that **we** will take, once an Editor creates a new post or revises an old post, right?

Could we migrate the above content into the [Editorial Process](https://docs.google.com/document/d/12fK83nnFPTq91ut0eFTUeVq9oW6XuVc1CtX6UZlk7R4/edit) document, and put the "Editors Workflow" and "Founders Workflow" side-by-side? It would be helpful to have these instructions in an easier to edit (and to refer back to, long-term) format than in GH comments.

If that's OK with you both, I can try to move them (would probably help me understand them better, tbh).
