### ISSUE TITLE
Draft editorial workflow for reviewing new and updates metrics posts

### ISSUE THREAD

**Issue by rchampieux** [Metrics-Toolkit/Metrics-Toolkit#53]

**Comment by coateshl** [comment]
draft available at https://docs.google.com/document/d/12fK83nnFPTq91ut0eFTUeVq9oW6XuVc1CtX6UZlk7R4/edit

**Comment by rchampieux** [comment]
@skonkiel and @rchampieux will review.

**Comment by skonkiel** [comment]
Have left comments. 

One thing I'm _slightly_ concerned about is whether the average Editor will know enough about GitHub to make this process work in the first few months...I think it might be a steep learning curve. We might need to reevaluate our approach to managing work via GH if it presents problems.

**Comment by rchampieux** [comment]
Robin will take next pass at synthesizing workflows.
