### ISSUE TITLE
Update IF Metric Post

### ISSUE THREAD

**Issue by rchampieux** [Metrics-Toolkit/Metrics-Toolkit#8]
"clarify textual description of the JIF to indicate that it is proprietary and only applies to journals indexed in Web of Science; clarify attribution to ISI, Thomson Reuters, Clarivate Analytics"

**Comment by rchampieux** [comment]
@coateshl is working on wrapping up edits.  She'll ping us when ready for next review.

**Comment by rchampieux** [comment]
Robin should add revised post to site.

**Comment by skonkiel** [comment]
Adding a comment here in addition to on Slack. @rchampieux can you please update this post asap with the 'v2' edits in the GDoc? I think we're resolved all outstanding edits. Thanks!
